INSERT INTO STATUS (name) VALUES ('Confirmado'),('Cancelado'),('Atrasado');
INSERT INTO PILOTS (name) VALUES ('Alvin M. Johnston'),('Charles Lindbergh'),('Doru Davidovici'),('José Costa'),('Gabriel Voisin'),('Howard Hughes'),('Ricardo Kirk'),('João Ribeiro de Barros'),('Edu Chaves');
INSERT INTO CITIES (name) VALUES ('Brasília'),('São Paulo'),('Rio de Janeiro'),('Salvador'),('Belo Horizonte'),('Fortaleza'),('Curitiba'),('Recife'),('Porto Alegre');
INSERT INTO AIRPLANES (name) VALUES ('Airbus A300'),('Boeing 707'),('Boeing 757'),('Embraer ERJ-190'),('Boeing 787'),('Airbus A380');

INSERT INTO FLIGHTS (arrival_time,departure_time,airplane_id,arrival_city_id,departure_city_id,pilot_id,status_id) VALUES ('2018-02-15','2018-01-15',(SELECT ID FROM AIRPLANES WHERE NAME = 'Airbus A300'),(SELECT ID FROM CITIES WHERE NAME = 'Fortaleza'),(SELECT ID FROM CITIES WHERE NAME = 'Belo Horizonte'),(SELECT ID FROM PILOTS WHERE NAME = 'Howard Hughes'),(SELECT ID FROM STATUS WHERE NAME = 'Atrasado'));
INSERT INTO FLIGHTS (arrival_time,departure_time,airplane_id,arrival_city_id,departure_city_id,pilot_id,status_id) VALUES ('2018-01-11','2018-01-11',(SELECT ID FROM AIRPLANES WHERE NAME = 'Boeing 757'),(SELECT ID FROM CITIES WHERE NAME = 'Recife'),(SELECT ID FROM CITIES WHERE NAME = 'Porto Alegre'),(SELECT ID FROM PILOTS WHERE NAME = 'Ricardo Kirk'),(SELECT ID FROM STATUS WHERE NAME = 'Confirmado'));
INSERT INTO FLIGHTS (arrival_time,departure_time,airplane_id,arrival_city_id,departure_city_id,pilot_id,status_id) VALUES ('2018-01-11','2018-01-11',(SELECT ID FROM AIRPLANES WHERE NAME = 'Embraer ERJ-190'),(SELECT ID FROM CITIES WHERE NAME = 'São Paulo'),(SELECT ID FROM CITIES WHERE NAME = 'Salvador'),(SELECT ID FROM PILOTS WHERE NAME = 'Gabriel Voisin'),(SELECT ID FROM STATUS WHERE NAME = 'Confirmado'));
INSERT INTO FLIGHTS (arrival_time,departure_time,airplane_id,arrival_city_id,departure_city_id,pilot_id,status_id) VALUES ('2018-01-30','2018-01-30',(SELECT ID FROM AIRPLANES WHERE NAME = 'Airbus A380'),(SELECT ID FROM CITIES WHERE NAME = 'Porto Alegre'),(SELECT ID FROM CITIES WHERE NAME = 'Curitiba'),(SELECT ID FROM PILOTS WHERE NAME = 'José Costa'),(SELECT ID FROM STATUS WHERE NAME = 'Atrasado'));
INSERT INTO FLIGHTS (arrival_time,departure_time,airplane_id,arrival_city_id,departure_city_id,pilot_id,status_id) VALUES ('2018-02-01','2018-03-01',(SELECT ID FROM AIRPLANES WHERE NAME = 'Airbus A380'),(SELECT ID FROM CITIES WHERE NAME = 'Curitiba'),(SELECT ID FROM CITIES WHERE NAME = 'Recife'),(SELECT ID FROM PILOTS WHERE NAME = 'Edu Chaves'),(SELECT ID FROM STATUS WHERE NAME = 'Confirmado'));
INSERT INTO FLIGHTS (arrival_time,departure_time,airplane_id,arrival_city_id,departure_city_id,pilot_id,status_id) VALUES ('2018-01-14','2018-01-14',(SELECT ID FROM AIRPLANES WHERE NAME = 'Boeing 787'),(SELECT ID FROM CITIES WHERE NAME = 'Belo Horizonte'),(SELECT ID FROM CITIES WHERE NAME = 'Brasília'),(SELECT ID FROM PILOTS WHERE NAME = 'Doru Davidovici'),(SELECT ID FROM STATUS WHERE NAME = 'Cancelado'));
INSERT INTO FLIGHTS (arrival_time,departure_time,airplane_id,arrival_city_id,departure_city_id,pilot_id,status_id) VALUES ('2018-01-07','2018-01-07',(SELECT ID FROM AIRPLANES WHERE NAME = 'Boeing 707'),(SELECT ID FROM CITIES WHERE NAME = 'Salvador'),(SELECT ID FROM CITIES WHERE NAME = 'Rio de Janeiro'),(SELECT ID FROM PILOTS WHERE NAME = 'Charles Lindbergh'),(SELECT ID FROM STATUS WHERE NAME = 'Confirmado'));
INSERT INTO FLIGHTS (arrival_time,departure_time,airplane_id,arrival_city_id,departure_city_id,pilot_id,status_id) VALUES ('2018-01-22','2018-01-22',(SELECT ID FROM AIRPLANES WHERE NAME = 'Boeing 787'),(SELECT ID FROM CITIES WHERE NAME = 'Rio de Janeiro'),(SELECT ID FROM CITIES WHERE NAME = 'São Paulo'),(SELECT ID FROM PILOTS WHERE NAME = 'Alvin M. Johnston'),(SELECT ID FROM STATUS WHERE NAME = 'Atrasado'));

